### Importing required libraries and data


In [ ]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('spam_ham_dataset.csv')
data.head()

Unnamed: 0  ... label_num
0         605  ...         0
1        2349  ...         0
2        3624  ...         0
3        4685  ...         1
4        2030  ...         0

[5 rows x 4 columns]

In [3]:
data.drop('Unnamed: 0',axis=1,inplace=True)
data.head()

label                                               text  label_num
0   ham  Subject: enron methanol ; meter # : 988291\r\n...          0
1   ham  Subject: hpl nom for january 9 , 2001\r\n( see...          0
2   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...          0
3  spam  Subject: photoshop , windows , office . cheap ...          1
4   ham  Subject: re : indian springs\r\nthis deal is t...          0

### Data Analysis

In [4]:
data.shape

(5171, 3)

In [23]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5171 entries, 0 to 5170
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   label      5171 non-null   object
 1   text       5171 non-null   object
 2   label_num  5171 non-null   int64 
dtypes: int64(1), object(2)
memory usage: 121.3+ KB


In [5]:
data.label.value_counts()

ham     3672
spam    1499
Name: label, dtype: int64

In [6]:
X = data.text
y = data.label_num

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)
print(X_train.shape)
print(X_test.shape)

(3878,)
(1293,)


### Training model

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

# the data is in text form so we need to convert it in machine understandable 
# language.. hence we can using CountVectorizer() which  provides a simple way 
# to both tokenize a collection of text documents and build a vocabulary of known 
# words, but also to encode new documents using that vocabulary

###### Method 1

In [9]:
cv = CountVectorizer()
mulnomial_model = MultinomialNB()

In [10]:
X_count = cv.fit_transform(X_train)  

In [11]:
mulnomial_model.fit(X_count,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [12]:
X_count_test = cv.transform(X_test)

In [13]:
mulnomial_model.score(X_count_test,y_test)*100 # acuracy in %

97.37045630317091

In [14]:
# here I have extracted some mails from by gmail

# First and third mail is spam(1) and second is ham(0) or not-spam in the following list!
mail =["Subject:	Interested in preparing for SAT / GMAT / GRE?\nStart Your Online Test Prep Learning with TC Global Today!\nHi Prathamesh,\nEveryone worries about prepping for their SAT / GMAT / GRE. Are you worried too? You don’t need to! Cause at TC Global Learning, We got your back!\nWith all the competition looming around, Test Prep can be that intimidating monster! We understand you ( we’ve been in your shoes! ), and so do our experienced and qualified Test Prep Programme's faculty. We are aware of how difficult and daunting it can be and have designed a pedagogy to help ease your learning and have high scores!\nOur Virtual TC Global Learning Classes have been designed, keeping YOU in mind. They will\nExpose you to the world of online learning\nShowcase how many students like yourself are open to learning digitally\nAttend tutorials that are smaller in size, so you get individual attention from our faculty!\nAccess all study materials online!\nOur Learning platform has additional content like recordings of previous sessions, sectional tests and quizzes and so much more!\nPersonalized performance reviews and evaluation\nStart a new batch every week!\nBook your Free Online demo class today and see what we are talking about!\nCome, Join the Movement #comejointhemovement\nSpeak Soon,\nTC Global\n© 2019 The Chopras Global Holdings PTE Ltd - All rights reserved.​", 
       "Subject:letter for leave\nHi Prathamesh,\nhope you are doing well\nI'm writing this mail to inform you that I'm on leave from 1/5/20 to 5/5/20.\nThank you",
       "Subject: ETHNUS-FREE E certification Registration LINK\nDear Students,\nHope the Webinars were helpful & now its time for free certification!\n#Hurry Up#Rush To Get Free Aptitude Ecertificate#\nDue to popular demand, we have extended the deadline for clearing the eCertification till 10th April 2020 for the Aptitude topics covered in the Free 7-Day Masterclass.\nDo share with all your students of all 1st to 4th year of Engineering and your network...!image.png\nRegister on below link to get Free Ecertificate Test Link through email :-\nhttps://www.codemithra.com/registerdc\nEcertificate Test Link:\nhttps://learn.codemithra.com/login/index.php\nNote :-\n1. If you have gave the certification exam then already then we will send the eCertificate on or before 11th April 2020.\n2. If not took the test then register on the link to get the certification link.\n#Upcoming Programs#Save Your Dates!\nAlso we have Free demo classes on AWS & ORACLE Certification from 13th to 19th April at 7 pm daily on our  Telegram Channel to get the link to the webinar! https://t.me/ethnuscodemithra\n1.13th April :- Overview/ Benefits of ORACLE & AWS Certification.\n2. 14,15 & 16th April :- Insights of Oracle Complete Certification.\n3. 17, 18,19th April:- Insights of  AWS Complete Certification.\nPFA of Upcoming Poster Below!\nSend Hello Codemithra on 6362910073 to get direct updates on what's app! \nThanking You & Regards,\nDevraj Shinde| Customer Relations Manager\nBusiness Development\nEthnus - Bangalore\nMobile: +91 6362910073"]

In [15]:
print(mail[0])

Subject:	Interested in preparing for SAT / GMAT / GRE?
Start Your Online Test Prep Learning with TC Global Today!
Hi Prathamesh,
Everyone worries about prepping for their SAT / GMAT / GRE. Are you worried too? You don’t need to! Cause at TC Global Learning, We got your back!
With all the competition looming around, Test Prep can be that intimidating monster! We understand you ( we’ve been in your shoes! ), and so do our experienced and qualified Test Prep Programme's faculty. We are aware of how difficult and daunting it can be and have designed a pedagogy to help ease your learning and have high scores!
Our Virtual TC Global Learning Classes have been designed, keeping YOU in mind. They will
Expose you to the world of online learning
Showcase how many students like yourself are open to learning digitally
Attend tutorials that are smaller in size, so you get individual attention from our faculty!
Access all study materials online!
Our Learning platform has additional content like recor

In [16]:
mail_count = cv.transform(mail)  #encoding the text

In [17]:
mulnomial_model.predict(mail_count)     #it gives perfect results for classifying the mail samples 

array([1, 0, 1])

###### Method 2 

In [18]:
from sklearn.pipeline import Pipeline
model = Pipeline([
                ('Vectorize', CountVectorizer()),
                ('multinomial_model', MultinomialNB())
                ])

In [19]:
model.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('Vectorize',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('multinomial_model',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [20]:
model.predict(X_test)

array([0, 0, 0, ..., 1, 1, 0])

In [21]:
model.score(X_test, y_test)*100 # acuracy in %

97.37045630317091

In [22]:
model.predict(mail)

array([1, 0, 1])